Blog/ViewModels/EditPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Blog.ViewModels
{
    public class EditPasswordViewModel
    {
        [Required(ErrorMessage = "Pole musi zostać wypełnione.")]
        public String OldPassword { get; set; }

        [Required(ErrorMessage = "Pole musi zostać wypełnione.")]
        [MinLength(5, ErrorMessage = "Pole musi zawierać przynajmniej 5 znaki.")]
        public String NewPassword { get; set; }

        [Required(ErrorMessage = "Pole musi zostać wypełnione.")]
        [Compare("NewPassword", ErrorMessage="Pola haseł nie są ze sobą zgodne!")]
        public String ConfirmNewPassword { get; set; }
    }
}

Blog/ViewModels/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Blog.ViewModels
{
    public class RegisterViewModel
    {
        [Required(ErrorMessage="Pole musi zostać wypełnione.")]
        [MinLength(3, ErrorMessage="Pole musi zawierać przynajmniej 3 znaki.")]
        [MaxLength(15, ErrorMessage="Pole nie może zawierać więcej niż 15 znaków.")]
        public String UserName { get; set; }

        [Required(ErrorMessage = "Pole musi zostać wypełnione.")]
        [Compare("UserName", ErrorMessage="Pola nazwy użytkownika są niezgodne ze sobą.")]
        public String ConfirmUserName { get; set; }

        [Required(ErrorMessage = "Pole musi zostać wypełnione.")]
        [MinLength(5, ErrorMessage = "Pole musi zawierać przynajmniej 5 znaki.")]
        public String Password { get; set; }

        [Required(ErrorMessage = "Pole musi zostać wypełnione.")]
        [Compare("Password", ErrorMessage = "Pola hasła są niezgodne ze sobą.")]
        public String ConfirmPassword { get; set; }

        [Required(ErrorMessage = "Pole musi zostać wypełnione.")]
        [EmailAddress(ErrorMessage="Podany E-Mail jest w złym formacie.")]
        public String EMail { get; set; }

        [Required(ErrorMessage = "Pole musi zostać wypełnione.")]
        [Compare("EMail", ErrorMessage = "Pola adresu E-Mail są niezgodne ze sobą.")]
        public String ConfirmEMail { get; set; }
    }
}

Blog/Areas/Administrator/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Services;
using Blog.ViewModels;
using Microsoft.Practices.Unity;

namespace Blog.Areas.Administrator.Controllers
{
    public class SecurityController : Controller
    {
        private ISecurityService _securityService = null;

        public SecurityController(ISecurityService securityService)
        {
            _securityService = securityService;
        }

        [HttpGet]
        public ActionResult Auth()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Auth(AuthViewModel viewModel)
        {
            var result = _securityService.Login(viewModel);

            if (result)
                return RedirectToAction("Index", "Home", new { area = "Administrator" });
            else
            {
                TempData.Add("ErrorMsg", "Błąd w trakcie próby zalogowania się. Spróbuj ponownie!");
                return RedirectToAction("Auth");
            }
        }

        [HttpGet]
        public ActionResult Logout()
        {
            _securityService.LogOut();
            return RedirectToAction("Auth");
        }
	}
}

Blog/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using Blog.ViewModels;
using Blog.Services;
using Blog.Filters;

namespace Blog.Controllers
{
    public class SecurityController : Controller
    {
        private ISecurityService _securityService = null;
        private ISettingsService _settingsService = null;
        private ICaptchaService _captchaService = null;

        public SecurityController(ISecurityService securityService,
                                  ISettingsService settingsService,
                                  ICaptchaService captchaService)
        {
            _securityService = securityService;
            _settingsService = settingsService;
            _captchaService = captchaService;
        }

        public ActionResult Login(FormCollection viewModel)
        {
            if (viewModel["login"] == String.Empty || viewModel["password"] == String.Empty)
            {
                TempData.Add("ErrorMsg", "Nazwa użytkownika lub hasło zostały błędnie wypełnione. Spróbuj ponownie!");
                return Redirect(HttpContext.Request.UrlReferrer.ToString());
            }

            var authViewModel = new AuthViewModel()
            {
                Login = viewModel["login"],
                Password = viewModel["password"]
            };

            bool result = _securityService.Login(authViewModel);
            if (result)
                TempData.Add("SuccessMsg", "Zalogowano poprawnie!");
            else
                TempData.Add("ErrorMsg", "Nieprawidłowe dane, spróbuj ponownie!");

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Logout()
        {
            _securityService.LogOut();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(RegisterViewModel viewModel)
        {
            if (!_securityService.IsLogged())
            {
                var recaptcha_challenge_field = Request.Form["recaptcha_challenge_field"];
                var recaptcha_response_field = Request.Form["recaptcha_response_field"];
                var captchaResult = _captchaService.ValidateCode(recaptcha_response_field, recaptcha_challenge_field);
                if (!captchaResult)
                    return Content("Podany kod nie jest poprawny!");
            }

            var result = _securityService.Register(viewModel, _settingsService.GetSettings());
            if (result)
            {
                TempData.Add("ErrorMsg", "test");
                return JavaScript("location.href = \"/\"");
            }
            else
            {
                return Content("Rejestracja nieudana! Prawdopodobnie wpisana nazwa użytkownika lub EMail są już zarejestrowane. Spróbuj ponownie.");
            }
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditPassword()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult EditPassword(EditPasswordViewModel viewModel)
        {
            var result = _securityService.ChangePassword(viewModel);
            if (result)
            {
                TempData.Add("SuccessMsg", "Edycja hasła zakończona sukcesem!");
                return View();
            }
            else
            {
                TempData.Add("ErrorMsg", "Błąd podczas próby zmiany hasła. Prawdopodobnie źle wpisałeś swoje obecne hasło, spróbuj ponownie.");
                return View(viewModel);
            }
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditAccount()
        {
            var user = _securityService.Get(_securityService.GetCurrentID());
            return View(user);
        }

        [HttpPost]
        [Authorize]
        public ActionResult EditAccount(UserViewModel viewModel)
        {
            var result = _securityService.Edit(viewModel);
            if (result)
            {
                TempData.Add("SuccessMsg", "Edycja danych użytkownika zakończona sukcesem!");
                return RedirectToAction("EditAccount");
            }
            else
            {
                TempData.Add("ErrorMsg", "Błąd podczas próby zmiany danych profilu.");
                return View(viewModel);
            }
        }
	}
}

Blog/Views/Security/EditAccount.cshtml
@model Blog.ViewModels.UserViewModel

@{
    ViewBag.Title = "Edytuj konto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="article">
    @using (Html.BeginForm("EditAccount", "Security"))
    {
        <div class="form-group">
            <label for="inputEmail">Strona internetowa</label>
            @Html.TextBoxFor(p => p.WebSite, new { @class = "form-control", placeholder = "Strona internetowa" })
            @Html.ValidationMessageFor(p => p.WebSite, null, new { @class = "validation-message" })
        </div>
        
        <button type="submit" class="btn btn-primary register-button">Edytuj dane</button>
    }

    <div style="margin-top: 30px;">@Html.ActionLink("Przejdź do edycji hasła", "EditPassword", null, new { @class = "btn btn-primary" })</div>
</div>

Blog/Views/Security/EditPassword.cshtml
@model Blog.ViewModels.EditPasswordViewModel

@{
    ViewBag.Title = "Edytuj hasło";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="article">
    @using(Html.BeginForm("EditPassword", "Security"))
    {
        <div class="form-group">
            <label for="inputEmail">Stare hasło</label>
            @Html.TextBoxFor(p => p.OldPassword, new { @class = "form-control", type = "password", placeholder = "Stare hasło" })
            @Html.ValidationMessageFor(p => p.OldPassword, null, new { @class = "validation-message" })
        </div>
        
        <div class="form-group">
            <label for="inputEmail">Nowe hasło</label>
            @Html.TextBoxFor(p => p.NewPassword, new { @class = "form-control", type = "password", placeholder = "Nowe hasło" })
            @Html.ValidationMessageFor(p => p.NewPassword, null, new { @class = "validation-message" })
        </div>
        
        <div class="form-group">
            <label for="inputEmail">Potwierdź nowe hasło</label>
            @Html.TextBoxFor(p => p.ConfirmNewPassword, new { @class = "form-control", type = "password", placeholder = "Potwierdź nowe hasło" })
            @Html.ValidationMessageFor(p => p.ConfirmNewPassword, null, new { @class = "validation-message" })
        </div>
        
        <button type="submit" class="btn btn-primary register-button">Edytuj dane</button>
    }
</div>

Blog/Views/Security/Register.cshtml
@model Blog.ViewModels.RegisterViewModel

@{
    ViewBag.Title = "Rejestracja";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="article">
    @using (Ajax.BeginForm("Register", "Security", new { returnUrl = ViewBag.ReturnUrl }, new AjaxOptions() { UpdateTargetId = "validation-message" }))
    {
        <div class="form-group">
            <label for="inputEmail">Nazwa użytkownika</label>
            @Html.TextBoxFor(p => p.UserName, new { @class = "form-control", placeholder = "Nazwa użytkownika" })
            @Html.ValidationMessageFor(p => p.UserName, null, new { @class = "validation-message" })
        </div>
        
        <div class="form-group">
            <label for="inputEmail">Potwierdź nazwę użytkownika</label>
            @Html.TextBoxFor(p => p.ConfirmUserName, new { @class = "form-control", placeholder = "Nazwa użytkownika" })
            @Html.ValidationMessageFor(p => p.ConfirmUserName, null, new { @class = "validation-message" })
        </div>
        
        <div class="form-group">
            <label for="inputEmail">Hasło</label>
            @Html.TextBoxFor(p => p.Password, new { @class = "form-control", type = "password", placeholder = "Hasło" })
            @Html.ValidationMessageFor(p => p.Password, null, new { @class = "validation-message" })
        </div>
        
        <div class="form-group">
            <label for="inputEmail">Potwierdź hasło</label>
            @Html.TextBoxFor(p => p.ConfirmPassword, new { @class = "form-control", type = "password", placeholder = "Hasło" })
            @Html.ValidationMessageFor(p => p.ConfirmPassword, null, new { @class = "validation-message" })
        </div>
        
        <div class="form-group">
            <label for="inputEmail">E-Mail</label>
            @Html.TextBoxFor(p => p.EMail, new { @class = "form-control", placeholder = "E-Mail" })
            @Html.ValidationMessageFor(p => p.EMail, null, new { @class = "validation-message" })
        </div>
        
        <div class="form-group">
            <label for="inputEmail">Potwierdź E-Mail</label>
            @Html.TextBoxFor(p => p.ConfirmEMail, new { @class = "form-control", placeholder = "E-Mail" })
            @Html.ValidationMessageFor(p => p.ConfirmEMail, null, new { @class = "validation-message" })
        </div>

        <button type="submit" class="btn btn-primary register-button">Zarejestruj!</button>
        <div style="float: right;">@Html.Action("Captcha", "Modules")</div>
        <div id="validation-message"></div>
    }
</div>